Fix build with gcc-12
:Release Notes:

:Detailed Notes:
Fix build with gcc-12
* fixes:
  http://gecko.lge.com/Errors/Details/400132

FAILED: CMakeFiles/bluez5.dir/src/bluez5device.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ -Dbluez5_EXPORTS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot/usr/include/libmount -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot/usr/include/blkid -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot/usr/include/gio-unix-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/git/src -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/build/Configured/src -mcpu=cortex-a72 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2  -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5=/usr/src/debug/bluetooth-sil-bluez5/0.1.0-78-r5                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5=/usr/src/debug/bluetooth-sil-bluez5/0.1.0-78-r5                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++0x -pthread -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot/usr/include/libmount -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot/usr/include/blkid -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/recipe-sysroot/usr/lib/glib-2.0/include -pthread -Wl,--no-undefined -DUSE_SYSTEM_BUS_FOR_OBEX -DNDEBUG -fPIC -MD -MT CMakeFiles/bluez5.dir/src/bluez5device.cpp.o -MF CMakeFiles/bluez5.dir/src/bluez5device.cpp.o.d -o CMakeFiles/bluez5.dir/src/bluez5device.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/git/src/bluez5device.cpp
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluetooth-sil-bluez5/0.1.0-78-r5/git/src/bluez5device.cpp:49:41: error: variable 'const std::array<std::__cxx11::basic_string<char>, 4> supportedMessageTypes' has initializer but incomplete type
   49 | static const std::array<std::string, 4> supportedMessageTypes = {"EMAIL", "SMS_GSM", "SMS_CDMA", "MMS"};
      |                                         ^~~~~~~~~~~~~~~~~~~~~

:Testing Performed:
Tested locally

:QA Notes:
NA

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale

Change-Id: I8007d7f66b76e0b6c3f78d57d1ce21f86b2b121b